<?php
$lang = array(
// Misc
'empty' => "Sorry, no fields may be left empty.",
'saved' => "Information saved.",
'title' => "User Control Center",
'title_menu' => "Menu",
'title_content' => "Content",
'notepad_title' => "Notepad",
'notepad_button' => "Save Text",
'reset_form' => "Reset Form",
'yes' => "Yes",
'no' => "No",
// Menu
'menu_home'				=> "Overview",
'menu_avatar'			=> "Edit Avatar",
'menu_sig'				=> "Edit Signature",
'menu_sub_options'		=> "Options",
'menu_email'			=> "Change Email Address",
'menu_password'			=> "Change Password",
'menu_date'				=> "Date &amp; Time Settings",
'menu_settings'			=> "Board Settings",
'menu_email_settings'	=> "Email Settings",
'profile_button'		=> "Save Profile",
// Signature change
'sig_update'			=> "Your signature has been updated.",
'sig_edit'				=> "Edit signature",
'sig_your'				=> "Your current signature",
'sig_button'			=> "Save signature",
// Change email:
'email_same'			=> "Your old and new email addresses are the same.",
'email_match'			=> "The email addresses you entered do not match.",
// Password:
'pass_wrong_error'		=> "The password you entered does not match your current one, please try again",
'pass_same'				=> "Your new and old passwords are the same, please choose a new password.",
'pass_match'			=> "The passwords do not match.",
'pass_email_notice'		=> "Hi {$icebb->user['username']},\n\nYou have recieved this message as a notice about a password change of your account at {$icebb->config['site_name']}.\nYour username is: {$icebb->user['username']}\nYour new password is: {$icebb->input['pass_new']}\n\nIf you did not request this, please contact an administrator.\n\nThanks,\nThe {$icebb->config['site_name']} team",
'pass_email_subject'	=> "Password change (From {$config['site_name']})",
'pass_current'			=> "Current password",
'pass_new'				=> "New password:",
'pass_new_confirm'		=> "Confirm new password:",
'pass_button'			=> "Change Password",
// Avatar:
'av_current'			=> "Current avatar",
'av_pixels'				=> "pixels",
'av_change'				=> "Change avatar",
'av_upload'				=> "Upload",
'av_upload_desc'		=> "Leave blank to keep current upload",
'av_url'				=> "URL",
'av_none'				=> "No avatar",
'av_button'				=> "Save",
'av_up_link'			=> "Upload Avatar",
'av_del'				=> "Avatar deleted",
'av_not_del'			=> "Avatar could not be deleted.",
'avup_file' => "Avatar to upload:",
'avup_button' => "Upload Avatar",
'avup_success' => "Avatar uploaded and updated",
'avup_move' => "Could not move temporary file to uploads folder. Please contact an administrator.",
'avup_not_image' => "That is not an image.",
// Favorites:
'fav_title_name' => "Name",
'fav_title_options' => "Options",
'fav_none' => "<i>No favorites in list</i>",
'fav_del' => "Favorite deleted",
'fav_not_del' => "Favorite not deleted.",
// Email settings:
'es_title_setting' => "Setting",
'es_title_value' => "Value",
'es_admin' => "May board administrators contact you?",
'es_member' => "May other members contact you?",
'es_button' => "Save Settings",
// Away system:
'away_title' => "Away system",
'away_on_off' => "Do you wish to be shown as away?",
'away_reason' => "Reason:",
'away_button' => "Save Settings",
'away_status_updated' => "Your away status has been updated",
// 0.9.3
'no_uploads'			=> "You do not have any uploaded files...",
'pm_topics'				=> "PM Topics:",
'pm_posts'				=> "PM Posts:",
'pm_new'				=> "New PMs:",
'view_smileys'			=> "Do you wish to view smileys?",
'something_went_wrong'	=> "Something went wrong with your upload, please contact an administrator.",
'settings_updated'		=> "Your settings have been updated.",
'menu'					=> "Menu",
'personal_profile'		=> "Personal Profile",
'overview'				=> "Overview",
'edit_profile'			=> "Edit Profile",
'edit_avatar'			=> "Edit Avatar",
'edit_sig'				=> "Edit Signature",
'user_groups'			=> "User Groups",
'away_system'			=> "Away System",
'tools'					=> "Tools",
'buddy_list'			=> "Buddy List",
'manage_favs'			=> "Manage Favorites",
'manage_uploads'		=> "Manage Uploads",
'settings'				=> "Settings",
'enable_quick_edit'		=> "Do you wish to use quick edit (when available)?",
'account_info'			=> "Your Account Info",
'group'					=> "Group:",
'posts'					=> "Posts:",
'posts_per_day'			=> "%s per day",
'posts_view_all'		=> "View all",
'joined'				=> "Member Since:",
'favorite_topics'		=> "Favorite Topics",
'favorite_forums'		=> "Favorite Forums",
'your_notepad'			=> "Your Notepad",
'save_your_notes'		=> "Save your notes",
'save_profile'			=> "Save my Profile",
'clear'					=> "Clear",
'email_new'				=> "New e-mail address:",
'email_new_confirm'		=> "Confirm new e-mail address:",
'email_save'			=> "Change E-mail Address",
'your_uploads'			=> "Your uploads",
'rem'					=> "Remove",
'allow_admin_contact'	=> "Allow administrators to contact you?",
'allow_mem_contact'		=> "Allow a member send you an email?",
'save_settings'			=> "Save Settings",
'view_avs'				=> "Do you wish to view users avatars?",
'view_sigs'				=> "Do you wish to view users signatures?",
'editor_style'			=> "Editor style",
'editor_style_desc'		=> "Would you prefer a basic or advanced editor?",
'editor_1'				=> "Basic editor",
'editor_2'				=> "Extended editor",
'editor_3'				=> "WYSIWYG editor",
'skin_choice'			=> "Skin choice:",
'lang_choice'			=> "Language choice:",
'your_current_time'		=> "Your current time is %s",
'your_time_zone'		=> "What is your time zone?",
'enable_dst'			=> "Do you want your time to be automatically adjusted for daylight savings time?",
'date_format_select'	=> "What would you like your dateformat to be?",
'date_format_select_php'=> "(uses the PHP <a href='http://php.net/date'>date format</a>)?",
'iptools_resolves'		=> "Resolves to",
'iptools_members'		=> "Members using this IP",
'iptools_posts'			=> "Posts made using this IP",
'iptools_posts_post'	=> "Post #%d",
'by'					=> 'by',
'additional_info'		=> "Additional information",
'bud_buddies'			=> "Buddies",
'bud_blocked'			=> "Blocked",
'add'					=> "Add",
// 1.0
'user_not_found'		=> "Sorry, that user does not exist on this forum.",
'forum_default'			=> "Forum default",
'av_type_not_allowed'	=> "Sorry, but you may not upload that type of image on this forum.",
'openid_no_password'	=> "You do not have a password because you are using OpenID to login",
);
?>
